In [2]:
import numpy as np

#### Arrays

In [4]:
ar = np.array([[1,2,3],[4,5,6]], dtype="float64") # take sequence object and dtype
print(ar.ndim) # number of dimensions
print(ar.shape) # shape of ndarray
print(ar.dtype) # datatype of ndarray

2
(2, 3)
float64


In [7]:
ar1 = np.zeros(ar.shape) # make an ndarray filled with zeros take array shape or length as input (similar to np.ones)
ar1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
ar2 = np.empty((1,2)) # return ndarray with uninitialized memory
ar2

array([[1.05119723e-311, 0.00000000e+000]])

In [9]:
ar3 = np.arange(1,100,2) # return a ndarray range
ar3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [25]:
ar4 = np.identity(4) # identity matrix
ar4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Datatypes

In [47]:
a1 = np.array([1,2], dtype="int8") # upto 64 bits (can be unsigned if preceded with 'u')
a1

array([1, 2], dtype=int8)

In [49]:
a2 = np.array([1,2], dtype="float16") # upto 128 bits
a2

array([1., 2.], dtype=float16)

In [53]:
a3 = np.array((1,2), dtype="complex64") # upto 265 bits (represented by two 128-bit floats)
a3

array([1.+0.j, 2.+0.j], dtype=complex64)

In [51]:
a4 = np.array((1,0), dtype="bool") # boolean ndarray
a4

array([ True, False])

In [57]:
ar1_float = a1.astype(np.float64) # any ndarray can be casted to another type
ar1_float.dtype

dtype('float64')

In [64]:
ar_str = np.array([["123e5"],["0.005"]])
ar_str.astype(np.float64)

array([[1.23e+07],
       [5.00e-03]])

#### Arithmetics

In [33]:
my_arr = np.array([
    [5,16,23.7],
    [67, 0, 5.78]
])
my_arr * 2 # element wise operations

array([[ 10.  ,  32.  ,  47.4 ],
       [134.  ,   0.  ,  11.56]])

In [68]:
my_arr ** 3

array([[1.25000000e+02, 4.09600000e+03, 1.33120530e+04],
       [3.00763000e+05, 0.00000000e+00, 1.93100552e+02]])

In [70]:
my_arr - 2

array([[ 3.  , 14.  , 21.7 ],
       [65.  , -2.  ,  3.78]])

In [71]:
my_arr + 15

array([[20.  , 31.  , 38.7 ],
       [82.  , 15.  , 20.78]])

In [75]:
my_arr > ar1 # both arrays have to be of the same size

array([[ True,  True,  True],
       [ True, False,  True]])

#### Indexing & Slicing

In [85]:
Arr = np.arange(1,15)
Arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
Arr[3:8] # [start:end:step]

array([4, 5, 6, 7, 8])

In [88]:
Arr[2:13:2]

array([ 3,  5,  7,  9, 11, 13])

In [89]:
Arr[:6]

array([1, 2, 3, 4, 5, 6])

In [93]:
Arr[2:7] = 99 # values can be broadcasted to a section
Arr

array([ 1,  2, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

In [97]:
Arr_section = Arr[:3] # modifications of selected section reflect on original array
Arr_section[0] = 5
Arr

array([ 5,  2, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

In [103]:
copied_section = Arr[11:14].copy() # explicitly copy array
copied_section

array([12, 13, 14])

In [105]:
copied_section[2] = 128
copied_section

array([ 12,  13, 128])

In [106]:
Arr

array([ 5,  2, 99, 99, 99, 99, 99,  8,  9, 10, 11, 12, 13, 14])

#### Multidimintional Array Indexing & Slicing

In [11]:
_arr = np.array([
                [[1,2,3],[4,5,6]],
                [[1,2,3],[4,5,6,]],
                [[7,8,9],[10,11,12]]
                ])
_arr.shape

(3, 2, 3)

In [14]:
_arr[0:2,1:] = 0 # filling the last array from first two dimensions with 0
_arr

array([[[ 1,  2,  3],
        [ 0,  0,  0]],

       [[ 1,  2,  3],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

#### Boolean Indexing

In [172]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) # select items with value "Bob"
names=="Bob"

array([ True, False, False,  True, False, False, False])

In [178]:
(names=="Bob") | (names=="Joe") # selcet items with value "Bob" or "Will"

array([ True,  True, False,  True, False,  True,  True])

In [167]:
data = np.array([[4, 7, 9], [0, 2, 4], [-5, 6, 3], [0, 0, 0], [1, 2, 8],[-12, -4, 15], [3, 4, 3]])
data.shape

(7, 3)

In [173]:
data[names=="Will", 1:] # select items in data with corresponding name "Will" in names array, then slice from index 1 to end
# NOTE: the first axis of both arrays have to be equal

array([[6, 3],
       [2, 8]])

#### Fancy Indexing

In [185]:
__ar = np.array([[y for x in range(5)] for y in range(8)])
__ar

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7]])

In [188]:
__ar[[4,3,0,6]] # select rows in desirable order

array([[4, 4, 4, 4, 4],
       [3, 3, 3, 3, 3],
       [0, 0, 0, 0, 0],
       [6, 6, 6, 6, 6]])

#### Expressing Conditional Logic as Array Operations

In [34]:
xar = np.array([1,2,3,4,5])
yar = np.array([6,7,8,9,10])
boolar = np.array([True, False, True, True, False])
np.where(boolar, xar, yar) # If true element from first arr is chosen else it's chosen from second arr (have to have same shape)

array([ 1,  7,  3,  4, 10])

#### Mathematical and Statistical Methods

In [25]:
mArr = xar.copy()
mArr.sum()

np.int64(15)

In [26]:
mArr.mean()

np.float64(3.0)

In [29]:
mArr.std() # standard deviation

np.float64(1.4142135623730951)